# Generated by Django 5.2.5 on 2025-08-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('accademic', 'Accademic'), ('sports', 'Sports'), ('cultural', 'Cultural'), ('others', 'Others')], default='others', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='exam_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Exam fee per semester', max_digits=10),
        ),
        migrations.AddField(
            model_name='program',
            name='other_fees',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Any other applicable fees', max_digits=10),
        ),
        migrations.AddField(
            model_name='program',
            name='registration_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='One-time registration fee', max_digits=10),
        ),
        migrations.AddField(
            model_name='program',
            name='tuition_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Base tuition fee per semester', max_digits=10),
        ),
    ]
