# Generated by Django 5.2.5 on 2025-08-24 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_event_program_exam_fee_program_other_fees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financerecord',
            name='program',
            field=models.ForeignKey(blank=True, help_text='Program associated with this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_records', to='core.program'),
        ),
        migrations.AlterField(
            model_name='financerecord',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, editable=False, help_text='Balance after this transaction', max_digits=10),
        ),
    ]
