# Generated by Django 5.2.5 on 2025-08-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_financerecord_program_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financerecord',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='financerecord',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, editable=False, help_text='Remaining balance after this transaction', max_digits=10),
        ),
    ]
